<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $products = [
            [
                'sku' => 'SKU-1001',
                'name' => 'Kabellose Maus',
                'description' => 'Ergonomische kabellose Maus mit einstellbarer DPI und leisem Klick.',
                'price' => 29.99,
                'stock_quantity' => 58,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1002',
                'name' => 'Mechanische Tastatur',
                'description' => 'Mechanische RGB-Tastatur mit austauschbaren Switches.',
                'price' => 89.00,
                'stock_quantity' => 34,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1003',
                'name' => 'USB-C Hub',
                'description' => '7-in-1-USB-C-Hub mit HDMI, SD-Karten-Slot und Schnellladefunktion.',
                'price' => 49.50,
                'stock_quantity' => 73,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1004',
                'name' => 'Laptop-Ständer',
                'description' => 'Aluminium-Standfuß für bessere Haltung und Luftzirkulation.',
                'price' => 34.90,
                'stock_quantity' => 41,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1005',
                'name' => 'Noise-Cancelling-Headset',
                'description' => 'Over-Ear-Headset mit ANC und USB-Empfänger.',
                'price' => 129.00,
                'stock_quantity' => 9,
                'is_active' => false,
            ],
            [
                'sku' => 'SKU-1006',
                'name' => 'Full-HD-Webcam',
                'description' => 'Full-HD-Webcam mit integriertem Mikrofon und Autofokus.',
                'price' => 59.90,
                'stock_quantity' => 26,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1007',
                'name' => 'Portable SSD 1 TB',
                'description' => 'Schnelle externe SSD mit 1 TB Speicher und USB-C-Anschluss.',
                'price' => 119.00,
                'stock_quantity' => 18,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1008',
                'name' => 'Bluetooth-Lautsprecher',
                'description' => 'Kompakter Bluetooth-Lautsprecher mit kraftvollem Klang.',
                'price' => 44.90,
                'stock_quantity' => 52,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1009',
                'name' => '27 Zoll Monitor',
                'description' => '27-Zoll-IPS-Monitor mit hoher Farbdarstellung und dünnem Rand.',
                'price' => 229.00,
                'stock_quantity' => 0,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1010',
                'name' => 'Gaming-Mauspad',
                'description' => 'Großes Gaming-Mauspad mit rutschfester Unterseite.',
                'price' => 19.90,
                'stock_quantity' => 67,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1011',
                'name' => 'USB-Mikrofon',
                'description' => 'USB-Kondensatormikrofon für Streaming und Videokonferenzen.',
                'price' => 79.00,
                'stock_quantity' => 22,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1012',
                'name' => 'Dockingstation',
                'description' => 'Universelle Docking-Station mit mehreren Display-Ausgängen.',
                'price' => 149.00,
                'stock_quantity' => 11,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1013',
                'name' => 'Monitorhalterung',
                'description' => 'Stabile Halterung für zwei Monitore am Schreibtisch.',
                'price' => 69.90,
                'stock_quantity' => 25,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1014',
                'name' => 'USB-C Kabel 2m',
                'description' => 'Robustes USB-C-Kabel mit Schnellladefunktion.',
                'price' => 12.90,
                'stock_quantity' => 96,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1015',
                'name' => 'Laptop Rucksack',
                'description' => 'Wasserabweisender Rucksack mit 15-Zoll-Laptopfach.',
                'price' => 54.90,
                'stock_quantity' => 39,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1016',
                'name' => 'Bluetooth-Tastatur',
                'description' => 'Kompakte Tastatur für Tablet und Notebook.',
                'price' => 39.00,
                'stock_quantity' => 0,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1017',
                'name' => 'Smart Plug',
                'description' => 'Smarte WLAN-Steckdose mit App-Steuerung.',
                'price' => 17.90,
                'stock_quantity' => 81,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1018',
                'name' => 'WLAN Repeater',
                'description' => 'Erweitert die Reichweite deines Heimnetzwerks.',
                'price' => 34.50,
                'stock_quantity' => 33,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1019',
                'name' => 'IP Kamera',
                'description' => 'Sicherheitskamera mit Nachtsicht und Bewegungserkennung.',
                'price' => 89.90,
                'stock_quantity' => 20,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1020',
                'name' => 'NVMe SSD 2 TB',
                'description' => 'Sehr schnelle SSD für hohe Datenraten.',
                'price' => 189.00,
                'stock_quantity' => 0,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1021',
                'name' => 'Powerbank 20.000 mAh',
                'description' => 'Leistungsstarke Powerbank für unterwegs.',
                'price' => 49.90,
                'stock_quantity' => 58,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1022',
                'name' => 'HDMI-Kabel 3 m',
                'description' => '4K-fähiges HDMI-Kabel mit stabiler Signalübertragung.',
                'price' => 14.50,
                'stock_quantity' => 102,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1023',
                'name' => 'Tablet-Stift',
                'description' => 'Präziser Eingabestift für Zeichnen und Notizen.',
                'price' => 29.90,
                'stock_quantity' => 47,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1024',
                'name' => 'Grafiktablett',
                'description' => 'Grafiktablett für kreatives Arbeiten am PC.',
                'price' => 99.00,
                'stock_quantity' => 0,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1025',
                'name' => 'Mini-PC',
                'description' => 'Kompakter Desktop-PC für Office und Medien.',
                'price' => 329.00,
                'stock_quantity' => 0,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1026',
                'name' => 'Router AX',
                'description' => 'Wi-Fi-6-Router für hohe Geschwindigkeit.',
                'price' => 139.00,
                'stock_quantity' => 18,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1027',
                'name' => 'Netzwerk-Switch',
                'description' => '8-Port-Gigabit-Switch für stabile Verbindungen.',
                'price' => 42.90,
                'stock_quantity' => 36,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1028',
                'name' => '4K-Webcam',
                'description' => 'Webcam mit 4K-Auflösung für professionelle Calls.',
                'price' => 119.90,
                'stock_quantity' => 15,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1029',
                'name' => 'Headset-Ständer',
                'description' => 'Platzsparender Ständer für Over-Ear-Headsets.',
                'price' => 18.00,
                'stock_quantity' => 64,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1030',
                'name' => 'Mikrofonarm',
                'description' => 'Flexibler Schwenkarm für Podcast-Mikrofone.',
                'price' => 36.90,
                'stock_quantity' => 27,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1031',
                'name' => 'Ringlicht',
                'description' => 'LED-Ringlicht für Videoaufnahmen und Streams.',
                'price' => 27.90,
                'stock_quantity' => 49,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1032',
                'name' => 'USB Ventilator',
                'description' => 'Leiser Ventilator mit USB-Stromversorgung.',
                'price' => 15.90,
                'stock_quantity' => 70,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1033',
                'name' => 'Notebook-Kühlpad',
                'description' => 'Kühlpad mit zwei Lüftern für Laptops.',
                'price' => 32.00,
                'stock_quantity' => 40,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1034',
                'name' => 'Kabelloses Ladegerät',
                'description' => 'Qi-Ladegerät für kompatible Smartphones.',
                'price' => 24.90,
                'stock_quantity' => 55,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1035',
                'name' => 'Ethernet-Adapter',
                'description' => 'USB-C-auf-LAN-Adapter für stabile Netzwerkverbindung.',
                'price' => 21.50,
                'stock_quantity' => 62,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1036',
                'name' => 'Maus-Bungee',
                'description' => 'Halterung für Mauskabel gegen Kabelzug.',
                'price' => 11.90,
                'stock_quantity' => 88,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1037',
                'name' => 'Ladestation 4-Port',
                'description' => 'USB-Ladestation mit vier Schnellladeports.',
                'price' => 39.90,
                'stock_quantity' => 29,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1038',
                'name' => 'Desktop-Lautsprecher',
                'description' => 'Kompakte Stereo-Lautsprecher für den Schreibtisch.',
                'price' => 59.00,
                'stock_quantity' => 31,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1039',
                'name' => 'Bluetooth-Empfänger',
                'description' => 'Adapter für kabelloses Audio am PC.',
                'price' => 16.90,
                'stock_quantity' => 53,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1040',
                'name' => 'USB-Hub 4-Port',
                'description' => 'Erweitert einen USB-Anschluss um vier Ports.',
                'price' => 22.90,
                'stock_quantity' => 77,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1041',
                'name' => 'Kartenleser',
                'description' => 'Kartenleser für SD- und microSD-Karten.',
                'price' => 13.90,
                'stock_quantity' => 66,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1042',
                'name' => 'Gaming-Controller',
                'description' => 'Controller mit Vibrationsfeedback für PC-Gaming.',
                'price' => 49.00,
                'stock_quantity' => 24,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1043',
                'name' => 'DisplayPort-Kabel',
                'description' => 'Hochwertiges Kabel für hohe Bildwiederholraten.',
                'price' => 17.50,
                'stock_quantity' => 91,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1044',
                'name' => 'Kabel-Organizer',
                'description' => 'Set für ordentliches Kabelmanagement am Arbeitsplatz.',
                'price' => 9.90,
                'stock_quantity' => 110,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1045',
                'name' => 'Kamera-Fensterhalterung',
                'description' => 'Halterung für flexible Kamerapositionierung.',
                'price' => 25.00,
                'stock_quantity' => 21,
                'is_active' => false,
            ],
            [
                'sku' => 'SKU-1046',
                'name' => 'Ergo-Handballenauflage',
                'description' => 'Komfortable Auflage für Tastatur und Maus.',
                'price' => 19.50,
                'stock_quantity' => 45,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1047',
                'name' => 'Notebook-Schloss',
                'description' => 'Sicherheitskabel für Laptops am Arbeitsplatz.',
                'price' => 28.90,
                'stock_quantity' => 17,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1048',
                'name' => 'Display-Reinigungsset',
                'description' => 'Sanftes Reinigungsset für Monitore und Displays.',
                'price' => 12.00,
                'stock_quantity' => 74,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1049',
                'name' => 'Smartes Thermometer',
                'description' => 'Digitales Thermometer mit Bluetooth-Anbindung.',
                'price' => 31.90,
                'stock_quantity' => 28,
                'is_active' => true,
            ],
            [
                'sku' => 'SKU-1050',
                'name' => 'Überwachungssensor',
                'description' => 'Sensor für Temperatur und Luftfeuchtigkeit in Räumen.',
                'price' => 27.50,
                'stock_quantity' => 35,
                'is_active' => true,
            ],
        ];

        Product::query()->upsert($products, ['sku'], ['name', 'description', 'price', 'stock_quantity', 'is_active']);
    }
}
